// flow-typed signature: 0865b15c4bd67e7a8b2c7ea56cea68d6
// flow-typed version: <<STUB>>/@deecewan/commander_v^2.16.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@deecewan/commander'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@deecewan/commander' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@deecewan/commander/index' {
  declare module.exports: $Exports<'@deecewan/commander'>;
}
declare module '@deecewan/commander/index.js' {
  declare module.exports: $Exports<'@deecewan/commander'>;
}
