// flow-typed signature: b5f243ab9ecb1494daca6d5dcdb0e775
// flow-typed version: <<STUB>>/@deecewan/eslint-config-flow_v^0.0.7/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@deecewan/eslint-config-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@deecewan/eslint-config-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@deecewan/eslint-config-flow/index' {
  declare module.exports: $Exports<'@deecewan/eslint-config-flow'>;
}
declare module '@deecewan/eslint-config-flow/index.js' {
  declare module.exports: $Exports<'@deecewan/eslint-config-flow'>;
}
