// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Process = require("process");
var Filename = require("bs-platform/lib/js/filename.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function parse(json) {
  return /* record */[
          /* apiKey */Json_decode.field("apiKey", Json_decode.string, json),
          /* messages */Json_decode.field("messages", Json_decode.string, json),
          /* sourceLocale */Json_decode.field("sourceLocale", Json_decode.string, json),
          /* targetLocales */Json_decode.field("targetLocales", (function (param) {
                  return Json_decode.array(Json_decode.string, param);
                }), json),
          /* output */Json_decode.field("output", Json_decode.string, json)
        ];
}

function load(filename) {
  var path = filename ? filename[0] : Process.cwd() + (Filename.dir_sep + ".translaterc.json");
  return parse(JSON.parse(Fs.readFileSync(path, "utf8")));
}

exports.parse = parse;
exports.load = load;
/* fs Not a pure module */
