// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var pot_data = "\n# TITLE.\n# Copyright (C) YEAR some project\n# This file is distributed under the same licence as the `translation-io` package.\n# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.\n#\n#, fuzzy\n# msgid \"\"\n# msgstr \"\"\n\"Project-Id-Version: translation-io 1.0\"\n\"Report-Msgid-Bugs-To: contact@translation.io\"\n\"POT-Creation-Date: 2017-01-01 10:00+1000\"\n\"PO-Revision-Date: 2017-01-01 10:00+1000\"\n\"Last-Translator: FULL NAME <EMAIL@ADDRESS>\"\n\"Language-Team: LANGUAGE <L@li.org>\"\n\"MIME-Version: 1.0\"\n\"Content-Type: text/plain; charset=UTF-8\"\n\"Content-Transfer-Encoding: 8bit\"\n\"Plural-Forms: nplurals=INTEGER; plural=EXPRESSION;\"\n";

exports.pot_data = pot_data;
/* No side effect */
