// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Chalk = require("chalk");

function info(x) {
  console.log(Chalk.cyan(x));
  return /* () */0;
}

function success(x) {
  console.log(Chalk.green(x));
  return /* () */0;
}

function warn(x) {
  console.log(Chalk.yellow(x));
  return /* () */0;
}

function error(x) {
  console.log(Chalk.red(x));
  return /* () */0;
}

exports.info = info;
exports.success = success;
exports.warn = warn;
exports.error = error;
/* chalk Not a pure module */
