// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


function run(config) {
  console.log("Sync: " + config[/* apiKey */0]);
  return /* () */0;
}

exports.run = run;
/* No side effect */
