// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Process = require("process");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Log$TranslationIo = require("./Log.bs.js");

function fail(message) {
  Log$TranslationIo.error(message);
  Process.exit(1);
  return Pervasives.failwith(message);
}

function po_generator(obj) {
  return $$Array.fold_left((function (acc, str) {
                return acc + ("\n" + str);
              }), "", $$Array.map((function (param) {
                    return "msgctxt \"" + (param[0] + ("\"\nmsgid " + (JSON.stringify(param[1]) + "\nmsgstr \"\"\n")));
                  }), Js_dict.entries(obj)));
}

exports.fail = fail;
exports.po_generator = po_generator;
/* Js_dict Not a pure module */
